### ISSUE TITLE
random game crash at 1h play

### ISSUE THREAD

**Issue by sean24YT** [HatchesPls/GrandTheftAutoV-Cheat#50] opened 2023-02-09 17:02 UTC
playeing with some people. ik in discord and after about 1h or 1h and 30 min my game will just crash and close. while theres is fine. even tho they have difrent menu. idk if this is a menu issue. or maybe my game settings?

**Comment by sean24YT** [comment] 2023-02-09 19:00
myself. with latest one updated tho?

**Comment by HatchesPls** [comment] 2023-02-10 18:46
Especially because of the longer game session I would say it's very likely to be either the game itself being unstable or a modder crashing your game. if the instability is also reproducible in a private lobby we can look into this further.

**Comment by sean24YT** [comment] 2023-02-10 19:03
ill test this in private alone.

**Comment by Loko415** [comment] 2023-02-15 22:51
lol i know why this occurs. Sigscanner/anticheat crash

**Comment by sean24YT** [comment] 2023-02-16 03:39
@Loko415 will try to take this out and give it a go. also will try a ban test with thi out. if that even is a thing lol. thanks mate!

**Comment by HatchesPls** [comment] 2023-02-19 10:59
No concrete details provided and unable to reproduce myself, closing this (for now).

**Closed by HatchesPls** 2023-02-19 10:59 UTC

**Comment by sean24YT** [comment] 2023-02-19 11:01
just go play games with almost fully lobby for 2h game will start lagging a bit then crashes
